# template for server
app:
  host-url: http://localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jira
    username: ${DB_PROD_USERNAME:jira}
    password: ${DB_PROD_PASSWORD:JiraRush}

